version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hjk
      POSTGRES_PASSWORD: star8903
      POSTGRES_DB: hjk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local